name: Matrixdemo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [14,16,18]
                operating-system: [ubuntu-latest,window-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
          - name: Get code
            uses: actions/checkout@v4
          - name: Install NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node-version }}
          - name: Install dependencies
            run: npm ci
          - name: Build project
            run: npm build run